// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIS6UWKU9tTX6qlgxM0qQYnfRpzw-13IM',
    appId: '1:231305489444:web:e3926096ba06c7c92bfcb1',
    messagingSenderId: '231305489444',
    projectId: 'chat-app-eaeb6',
    authDomain: 'chat-app-eaeb6.firebaseapp.com',
    storageBucket: 'chat-app-eaeb6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwMH7yga6AtEChNX7WSouaZweT86I-ZJY',
    appId: '1:231305489444:android:5dfeea4008f46fa52bfcb1',
    messagingSenderId: '231305489444',
    projectId: 'chat-app-eaeb6',
    storageBucket: 'chat-app-eaeb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJutpvDUG-A81pZB751hoaGgLX3tfu1Jo',
    appId: '1:231305489444:ios:7f7f2db0f3b16eb32bfcb1',
    messagingSenderId: '231305489444',
    projectId: 'chat-app-eaeb6',
    storageBucket: 'chat-app-eaeb6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJutpvDUG-A81pZB751hoaGgLX3tfu1Jo',
    appId: '1:231305489444:ios:63922d9287acd8032bfcb1',
    messagingSenderId: '231305489444',
    projectId: 'chat-app-eaeb6',
    storageBucket: 'chat-app-eaeb6.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
